services:
  backend:
    build:
      context: ./backend

    container_name: smartretail-backend

    ports:
      - "8000:8000"

    env_file:
      - ./backend/.env

    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16

    container_name: smartretail-postgres

    environment:
      POSTGRES_DB: smartretail
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

    container_name: smartretail-redis

    ports:
      - "6379:6379"

volumes:
  postgres_data: