apiVersion: v1
kind: Secret

metadata:
  name: smartretail-db-secret
  namespace: smartretail

type: Opaque

stringData:
  DATABASE_URL: "postgresql://USERNAME:PASSWORD@RDS-ENDPOINT:5432/smartretail"
  REDIS_URL: "redis://REDIS-ENDPOINT:6379"
  SECRET_KEY: "your-strong-secret-key"
