apiVersion: v1
kind: Service
metadata:
  name: {{include "smartretail.fullname" .}}
  labels: {{- include "smartretail.labels" . | nindent 4 }}
spec:
  type: {{.Values.service.type }}
  ports:
    - port: {{.Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector: {{- include "smartretail.selectorLabels" . | nindent 4 }}
